image: gitpod/workspace-flutter
tasks:
  - name: Calculator
    init: flutter run --web-port 8080
ports:
  - port: 8080
    onOpen: open-preview
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addBadge: true
vscode:
  extensions:
    - Dart-Code.flutter@3.12.1:7nojBobAyiqZHzEQDjcyxA==
    - Dart-Code.dart-code@3.12.1:CQFJ6nKQjwl1j2FxQCT1MA==
